### ISSUE TITLE
fastg link is broken (Sourceforge is down)

### ISSUE THREAD

**Issue by sauloal** [sjackman/assembly-graph#1]

**Comment by sjackman** [comment]
> This sourceforge.net website is temporarily offline.
> We are working hard to restore its availability. Please refer to the SourceForge.net Blog for updates.

**Comment by sjackman** [comment]
Here's a link to Google's cache of the PDF:
[FASTG_Spec_v1.00.pdf](http://webcache.googleusercontent.com/search?q=cache:YuSMoYkQnuQJ:fastg.sourceforge.net/FASTG_Spec_v1.00.pdf+&cd=1&hl=en&ct=clnk&gl=ca)
